### ISSUE TITLE
UI trading exchange

### ISSUE THREAD

**Issue by marcosmartinezfco** [blofin/blofin-ui#26]
I have one question, is this the library used to build this [website](https://blofin.com/spot/BTC-USDT)? The documentation is not clear but I'm really interested

**Comment by hly1445** [comment]
Yes, this is a React component library

**Comment by marcosmartinezfco** [comment]
> Yes, this is a React component library.Because I am usually very busy, I sometimes overlook some information. I apologize for that.

Yes but which one is it?

**Comment by hly1445** [comment]
Yes.the [website](https://blofin.com/spot/BTC-USDT) all common components are here.

**Comment by marcosmartinezfco** [comment]
> Yes.the [website](https://blofin.com/spot/BTC-USDT) all common components are here.

yeah i can see the website but what libraries are you using? I'd like to use it for a personal project. But I need the library of documentation for the components

**Comment by hly1445** [comment]
You can install blofin-ui in Nextjs/React. You can use the clone project. Run yarn storybook to view the document. Here are examples of all components

**Comment by marcosmartinezfco** [comment]
can you please send me the links? I didn't find any documentation or library/components I could install

**Comment by hly1445** [comment]
If there are any issues, feel free to contact me on Telegram: https://t.me/leo1445.

**Comment by hly1445** [comment]
This is the [link](https://www.npmjs.com/package/blofin-ui) to the npm package, and this repository contains the source code
